# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/api/games"
  to = "https://www.freetogame.com/api/games"
  status = 200

  [[redirects]]
  from = "/api/game"
  to = "https://www.freetogame.com/api/game"
  status = 200
  query = {id = ":id"}

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"